### ISSUE TITLE
Formater, linting and coding standards

### ISSUE THREAD

**Issue by simonsouter** [cakesolutions/sbt-cake#53]
My comments on the configuration of these plugins.  I'd like to see a process of consensus and refinement. 

In general and in my opinion the checks are too strict to be widely agreeable.  A more lenient set of checks that provide the most value should be the objective.

**Scalastyle + scalafmt:**
- 80 line width is too small.  Suggest 120 at least.

**Scalastyle:**
- Error level is too strict.  Warning is sufficient.

**Wart remover:**
Seems to report a lot of questionable and opinionated issues.  I would prefer to loosen the checks.  Sprinkling suppress warnings annotations around the codebase is not ideal.
 
- discarded non-Unit value
- Function has default arguments (crazy)
- case classes must be final (pointless)
- Inferred type containing Any
- Statements must return Unit
- throw is disabled (pointless)

**Comment by markglh** [comment]
My thoughts:
**Scalastyle + scalafmt:**
- 80 line width is too small.  Suggest 120 at least. **agreed**

**Scalastyle:**
- Error level is too strict.  Warning is sufficient. **I personally think we should only have scalafmt, and that it should fail the build if code isn't formatted**

**Wart remover:**
Seems to report a lot of questionable and opinionated issues.  I would prefer to loosen the checks.  Sprinkling suppress warnings annotations around the codebase is not ideal.
 
- discarded non-Unit value **I don't agree, this isn't that common and you can disable in line**
- Function has default arguments (crazy)*agreed*
- case classes must be final (pointless) **Indifferent**
- Inferred type containing Any **Can you give an example of this one causing you issues?**
- Statements must return Unit **indifferent, can you give an example which might sway me?**
- throw is disabled (pointless) **what're you throwing, Rod?**

**Comment by tudorzgureanu** [comment]
+1 to 120 line width and use only scalafmt

**Comment by felixt-cake** [comment]
Ditto: +1 to 120 line width and use only scalafmt.

The WartRemover spam seems useless to me.  I don't care about 66% of the warts mentioned :-D

**Comment by dhpiggott** [comment]
>In general and in my opinion the checks are too strict to be widely agreeable. A more lenient set of checks that provide the most value should be the objective.

Agree.

>80 line width is too small. Suggest 120 at least.

I've always gone with 120, and was initially irritated by 80. I've mostly got used to it and don't feel as strongly about it as some other things, but would still be happy to see it changed to 120.

> Error level is too strict. Warning is sufficient.

Disagree. I've seen warnings accumulate over time to the point that there are so many they are just ignored. Making them fatal prevents the accumulation, so each one is reviewed and then fixed or suppressed before ever being committed or merged.

>> I personally think we should only have scalafmt, and that it should fail the build if code isn't formatted

Yep, this, plus enabling extra scalac flags*, but no Scalastyle or Wartremover. We could selectively add a subset of the existing Scalastlye rules back over time, but given the choice of everything that's there or none of it, I'd go with none of it.

>Wart remover:
>Seems to report a lot of questionable and opinionated issues. I would prefer to loosen the checks. Sprinkling suppress warnings annotations around the codebase is not ideal.

Agree. Some things end up needing to be suppressed so often that we could all become blind to the suppressions, and so not actually spot the cases where the "wart" was something that really was an issue.

>discarded non-Unit value

Would prefer to keep this enabled.

>Function has default arguments (crazy)

Agree.

>case classes must be final (pointless)

Not entirely pointless - it does prevent the mistake of extending a case class. But then review can catch that.

>Inferred type containing Any

Agree.

>Statements must return Unit

Not sure what this one is.

>throw is disabled (pointless)

Agree.

*i.e. something like this: https://github.com/dhpcs/scala-json-rpc/blob/8aea1c1c049794bb21d850958bd7d6f1bdb7a159/project/CommonSettingsPlugin.scala#L29

**Comment by carlpulley** [comment]
Wrt the questions regarding line length: the one argument I've heard for shorter line lengths (e.g. 80) is that it allows some developers to compare 2-3 text files side by side in their IDEs. I'd argue that any resolution of this particular question should take into account this point of view.

**Comment by carlpulley** [comment]
Wrt scalastyle being at warning rather than error - disagree. As others have pointed out, you set things to warning and they will get ignored!

**Comment by carlpulley** [comment]
wrt Wartremover - totally agree that this tool (and this also holds for scalastyle and scalafmt) needs further tuning to arrive at a good set of enabled checks.

The approach I've taken in the past to this type of tuning is to apply strict checking and then sprinkle disable annotations/comments throughout the code base. At this point in time simple greps enable you to work out which things need disabling.

**Comment by carlpulley** [comment]
Wrt the question of scalafmt vs scalastyle: I'd argue that until scalafmt can support the things that scalastyle has (e.g. decent import ordering checks), then we use both. We should be using both tools in a mutually exclusive manner - that way they don't bump into each other!

To disable one tool because everyone is willing to give up style checking features in favour of automation is simply non-sensical. We need to better manage the issues here.
