### ISSUE TITLE
Permissive Default License

### ISSUE THREAD

**Issue by Slakah** [cakesolutions/sbt-cake#59]
Looking at line https://github.com/cakesolutions/sbt-cake/blob/e686d5d7e1addbaaa0db25014aecedbd676f8ac3/build.sbt#L31. This feels a little dangerous, I doubt most of our internal projects are actually Apache licensed projects, and it feels a little too easy to forget to remove this license.

I would have thought that we would probably default to an all rights reserved license, allowing any project maintainer to easily amend to a more permissive license. ([IANAL](https://en.wikipedia.org/wiki/IANAL)), but I would imagine that once a piece of source code is issued with a permissive license, then that license would be applied forever (it's not possible to remove the permissions granted by that license).

I'm all for open software, but it should be a conscious choice by the owner/maintainer of the software in question.

**Comment by carlpulley** [comment]
I'm not sure I agree with this?

These build.sbt settings apply (or rather should!) to sbt-cake only - hence why it has a permissive license. For BAMTech Media uses of sbt-cake, we fully expect that teams will define there own licenses (probably not relevant now for BAMTech Media projects?).

**Comment by Slakah** [comment]
> I'm not sure I agree with this?

> These build.sbt settings apply (or rather should!) to sbt-cake only - hence why it has a permissive license. For BAMTech Media uses of sbt-cake, we fully expect that teams will define there own licenses (probably not relevant now for BAMTech Media projects?).

![Doh!](https://media.giphy.com/media/xT5LMESsx1kUe8Hiyk/giphy.gif)


Raised this against the wrong repo, meant to raise this against https://github.com/cakesolutions/play-scala-template.g8 .

Apologies!

Edit: the proper issue https://github.com/cakesolutions/play-scala-template.g8/issues/55
