### ISSUE TITLE
manage wartremover differently for compile and test configs

### ISSUE THREAD

**Issue by fommil** [cakesolutions/sbt-cake#7]
@pjrt ^^^

**Comment by pjrt** [comment]
I was trying to do this along with unification, but then I realize I have no idea how SBT plugins work. I was thinking of having some sort of "compileSettings" and "testSettings" that get implemented by the user downsteam, but sbt plugins aren't "traits", so I'm not sure if that's possible.

**Comment by fommil** [comment]
No worries, there are about 5 people on the planet who understand sbt, all suffering. I'll do this on Monday.
